#pragma once
#include <iostream>
enum EnumVzdelanie
{
	BEZ_UKONCENEHO_VZDELANIA_0_14_ROKOV = 0,
	ZAKLADNE_VZDELANIE = 1,
	STREDNE_ODBORNE_VZDELANIE = 2,
	UPLNE_STREDNE_VZDELANIE = 3,
	VYSSIE_ODBORNE_VZDELANIE = 4,
	VYSOKOSKOLSKE_VZDELANIE = 5,
	BEZ_SKOLSKEHO_VZDELANIA_15_A_VIAC_ROKOV = 6,
	NEZISTENE = 7,
	NULL_ENUM_VZDELANIE = -1
};

